-- begin RULESMODULE_RULE_MANAGER_RULE_DATA_SCRIPT_LINK
alter table RULESMODULE_RULE_MANAGER_RULE_DATA_SCRIPT_LINK add constraint FK_RRMRDSL_RULE_MANAGER foreign key (RULE_MANAGER_ID) references RULESMODULE_RULE_MANAGER(ID)^
alter table RULESMODULE_RULE_MANAGER_RULE_DATA_SCRIPT_LINK add constraint FK_RRMRDSL_RULE_DATA_SCRIPT foreign key (RULE_DATA_SCRIPT_ID) references RULESMODULE_RULE_DATA_SCRIPT(ID)^
-- end RULESMODULE_RULE_MANAGER_RULE_DATA_SCRIPT_LINK
-- begin RULESMODULE_RULE_MANAGER_RULE_SCRIPT_LINK
alter table RULESMODULE_RULE_MANAGER_RULE_SCRIPT_LINK add constraint FK_RRMRSL_RULE_MANAGER foreign key (RULE_MANAGER_ID) references RULESMODULE_RULE_MANAGER(ID)^
alter table RULESMODULE_RULE_MANAGER_RULE_SCRIPT_LINK add constraint FK_RRMRSL_RULE_SCRIPT foreign key (RULE_SCRIPT_ID) references RULESMODULE_RULE_SCRIPT(ID)^
-- end RULESMODULE_RULE_MANAGER_RULE_SCRIPT_LINK
-- begin RULESMODULE_RULE_DATA_SCRIPT
create unique index IDX_RULESMODULE_RULE_DATA_SCRIPT_UK_NAME on RULESMODULE_RULE_DATA_SCRIPT (NAME) where DELETE_TS is null ^
-- end RULESMODULE_RULE_DATA_SCRIPT
