-- begin REVIEWS_MODERATION_PROPERTY
create unique index IDX_REVIEWS_MODERATION_PROPERTY_UK_ENTITY on REVIEWS_MODERATION_PROPERTY (ENTITY) where DELETE_TS is null ^
-- end REVIEWS_MODERATION_PROPERTY
-- begin REVIEWS_ENTITIES_FOR_MODERATION
alter table REVIEWS_ENTITIES_FOR_MODERATION add constraint FK_REVIEWS_ENTITIES_FOR_MODERATION_MODERATION_PROPERTY foreign key (MODERATION_PROPERTY_ID) references REVIEWS_MODERATION_PROPERTY(ID)^
create index IDX_REVIEWS_ENTITIES_FOR_MODERATION_MODERATION_PROPERTY on REVIEWS_ENTITIES_FOR_MODERATION (MODERATION_PROPERTY_ID)^
-- end REVIEWS_ENTITIES_FOR_MODERATION
-- begin REVIEWS_REVIEW
alter table REVIEWS_REVIEW add constraint FK_REVIEWS_REVIEW_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
create index IDX_REVIEWS_REVIEW_AUTHOR on REVIEWS_REVIEW (AUTHOR_ID)^
-- end REVIEWS_REVIEW
-- begin REVIEWS_MODERATION_PROPERTY_USER_LINK
alter table REVIEWS_MODERATION_PROPERTY_USER_LINK add constraint FK_MODPROUSE_MODERATION_PROPERTY foreign key (MODERATION_PROPERTY_ID) references REVIEWS_MODERATION_PROPERTY(ID)^
alter table REVIEWS_MODERATION_PROPERTY_USER_LINK add constraint FK_MODPROUSE_USER foreign key (USER_ID) references SEC_USER(ID)^
-- end REVIEWS_MODERATION_PROPERTY_USER_LINK
-- begin REVIEWS_ENTITIES_FOR_MODERATION_USER_LINK
alter table REVIEWS_ENTITIES_FOR_MODERATION_USER_LINK add constraint FK_ENTFORMODUSE_ENTITIES_FOR_MODERATION foreign key (ENTITIES_FOR_MODERATION_ID) references REVIEWS_ENTITIES_FOR_MODERATION(ID)^
alter table REVIEWS_ENTITIES_FOR_MODERATION_USER_LINK add constraint FK_ENTFORMODUSE_USER foreign key (USER_ID) references SEC_USER(ID)^
-- end REVIEWS_ENTITIES_FOR_MODERATION_USER_LINK
