-- begin IMPORTMODULE_TEST
alter table IMPORTMODULE_TEST add constraint FK_IMPORTMODULE_TEST_CHILD foreign key (CHILD_ID) references IMPORTMODULE_CHILD(ID)^
alter table IMPORTMODULE_TEST add constraint FK_IMPORTMODULE_TEST_TEST_COMP foreign key (TEST_COMP_ID) references IMPORTMODULE_TEST_COMP(ID)^
create index IDX_IMPORTMODULE_TEST_CHILD on IMPORTMODULE_TEST (CHILD_ID)^
-- end IMPORTMODULE_TEST
