-- begin DISCUSS_COMMENT
alter table DISCUSS_COMMENT add constraint FK_DISCUSS_COMMENT_PARENT foreign key (PARENT_ID) references DISCUSS_COMMENT(ID)^
alter table DISCUSS_COMMENT add constraint FK_DISCUSS_COMMENT_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
create index IDX_DISCUSS_COMMENT_PARENT on DISCUSS_COMMENT (PARENT_ID)^
create index IDX_DISCUSS_COMMENT_AUTHOR on DISCUSS_COMMENT (AUTHOR_ID)^
-- end DISCUSS_COMMENT
