-- begin DOCUMENTS_DOCUMENT
alter table DOCUMENTS_DOCUMENT add constraint FK_DOCUMENTS_DOCUMENT_ON_DOCUMENT_TYPE foreign key (DOCUMENT_TYPE_ID) references DOCUMENTS_DOCUMENT_TYPE(ID)^
create index IDX_DOCUMENTS_DOCUMENT_ON_DOCUMENT_TYPE on DOCUMENTS_DOCUMENT (DOCUMENT_TYPE_ID)^
-- end DOCUMENTS_DOCUMENT
-- begin DOCUMENTS_DOCUMENT_TYPE
alter table DOCUMENTS_DOCUMENT_TYPE add constraint FK_DOCUMENTS_DOCUMENT_TYPE_ON_PARENT foreign key (PARENT_ID) references DOCUMENTS_DOCUMENT_TYPE(ID)^
create index IDX_DOCUMENTS_DOCUMENT_TYPE_ON_PARENT on DOCUMENTS_DOCUMENT_TYPE (PARENT_ID)^
-- end DOCUMENTS_DOCUMENT_TYPE
-- begin DOCUMENTS_DOCUMENT_FILE_DESCRIPTOR_LINK
alter table DOCUMENTS_DOCUMENT_FILE_DESCRIPTOR_LINK add constraint FK_DOCFILDES_ON_DOCUMENT foreign key (DOCUMENT_ID) references DOCUMENTS_DOCUMENT(ID)^
alter table DOCUMENTS_DOCUMENT_FILE_DESCRIPTOR_LINK add constraint FK_DOCFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end DOCUMENTS_DOCUMENT_FILE_DESCRIPTOR_LINK

-- begin DOCUMENTS_DOCUMENT_RESTRICTION_DOCUMENT_TYPE_LINK
alter table DOCUMENTS_DOCUMENT_RESTRICTION_DOCUMENT_TYPE_LINK add constraint FK_DOCRESDOCTYP_ON_DOCUMENT_RESTRICTION foreign key (DOCUMENT_RESTRICTION_ID) references DOCUMENTS_DOCUMENT_RESTRICTION(ID)^
alter table DOCUMENTS_DOCUMENT_RESTRICTION_DOCUMENT_TYPE_LINK add constraint FK_DOCRESDOCTYP_ON_DOCUMENT_TYPE foreign key (DOCUMENT_TYPE_ID) references DOCUMENTS_DOCUMENT_TYPE(ID)^
-- end DOCUMENTS_DOCUMENT_RESTRICTION_DOCUMENT_TYPE_LINK

-- begin DOCUMENTS_DOCUMENT_RESTRICTION
create unique index IDX_DOCUMENTS_DOCUMENT_RESTRICTION_UK_KEY_ on DOCUMENTS_DOCUMENT_RESTRICTION (KEY_) where DELETE_TS is null ^
-- end DOCUMENTS_DOCUMENT_RESTRICTION
