-- begin NOTIFICATIONSUSERS_MESSAGE
alter table NOTIFICATIONSUSERS_MESSAGE add constraint FK_NOTIFICATIONSUSERS_MESSAGE_ON_SENDER foreign key (SENDER_ID) references SEC_USER(ID)^
alter table NOTIFICATIONSUSERS_MESSAGE add constraint FK_NOTIFICATIONSUSERS_MESSAGE_ON_RECIPIENT foreign key (RECIPIENT_ID) references SEC_USER(ID)^
alter table NOTIFICATIONSUSERS_MESSAGE add constraint FK_NOTIFICATIONSUSERS_MESSAGE_ON_MESSAGE_TEXT foreign key (MESSAGE_TEXT_ID) references NOTIFICATIONSUSERS_MESSAGE_TEXT(ID)^
alter table NOTIFICATIONSUSERS_MESSAGE add constraint FK_NOTIFICATIONSUSERS_MESSAGE_ON_META foreign key (META_ID) references NOTIFICATIONSUSERS_MESSAGE_META(ID)^
alter table NOTIFICATIONSUSERS_MESSAGE add constraint FK_NOTIFICATIONSUSERS_MESSAGE_ON_ATTACHMENT foreign key (ATTACHMENT_ID) references SYS_FILE(ID)^
create index IDX_NOTIFICATIONSUSERS_MESSAGE_ON_SENDER on NOTIFICATIONSUSERS_MESSAGE (SENDER_ID)^
create index IDX_NOTIFICATIONSUSERS_MESSAGE_ON_RECIPIENT on NOTIFICATIONSUSERS_MESSAGE (RECIPIENT_ID)^
create index IDX_NOTIFICATIONSUSERS_MESSAGE_ON_MESSAGE_TEXT on NOTIFICATIONSUSERS_MESSAGE (MESSAGE_TEXT_ID)^
create index IDX_NOTIFICATIONSUSERS_MESSAGE_ON_META on NOTIFICATIONSUSERS_MESSAGE (META_ID)^
create index IDX_NOTIFICATIONSUSERS_MESSAGE_ON_ATTACHMENT on NOTIFICATIONSUSERS_MESSAGE (ATTACHMENT_ID)^
-- end NOTIFICATIONSUSERS_MESSAGE
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
-- end SEC_USER
